name: npm-publish

on:
  push:
    # branches:
    #   - 'releases/**'
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.20.0
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: pnpm i && pnpm build
      - name: Publish package on NPM 📦
        run: cd build && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
